name: mini_play_party_server

services:
  # prod api
  api:
    profiles:
      - testing
    image: miniplayparty-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3336:3336
    environment:
      TZ: UTC
      LOG_LEVEL: info
      APP_KEY: zjYGaHD_JuJcjBs2t_AcaUFxd-cYyr4x
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: miniplay
      DB_PASSWORD: miniplay
      DB_DATABASE: miniplay
      DB_SSL: false
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: password
    depends_on:
      - redis
      - db

  redis:
    image: redis
    environment:
      REDIS_ARGS: '--requirepass password'
    ports:
      - 6379:6379

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: miniplay
      POSTGRES_USER: miniplay
      POSTGRES_DB: miniplay
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 9000:8080
    environment:
      SWAGGER_JSON: /api/swagger.json
    volumes:
      - ./ressources/api_spec.yaml:/api/swagger.json
