# fly.toml app configuration file generated for miniplayparty on 2025-05-09T14:37:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miniplayparty'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3336
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256