/* tslint:disable */
/* eslint-disable */
/**
 * Mini Play Party API
 * Mini Play Party API Spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@faisalhussain.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

