apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniplayparty-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniplayparty-api
  template:
    metadata:
      labels:
        app: miniplayparty-api
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z -v redis-service 6379; do echo Waiting for Redis; sleep 2; done;']
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z -v postgres-service 5432; do echo Waiting for PostgreSQL; sleep 2; done;']
      - name: migration
        image: ghcr.io/faisalhussain95/miniplayparty:main
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        command: ["node", "ace", "migration:run", "--force"]
        envFrom:
        - configMapRef:
            name: miniplayparty-api-config
        - secretRef:
            name: miniplayparty-api-secret
      containers:
      - name: miniplayparty-api
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        image: ghcr.io/faisalhussain95/miniplayparty:main
        ports:
        - containerPort: 3336
        readinessProbe:
          httpGet:
            path: /
            port: 3336
            httpHeaders:
            - name: Accept
              value: application/json
        envFrom:
        - configMapRef:
            name: miniplayparty-api-config
        - secretRef:
            name: miniplayparty-api-secret
