apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniplayparty-api-deployment
  namespace: miniplayparty-api-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniplayparty-api
  template:
    metadata:
      labels:
        app: miniplayparty-api
    spec:
      initContainers:
      - name: migration
        image: ghcr.io/faisalhussain95/miniplayparty:main
        command: ["node", "ace", "migration:run", "--force"]
        envFrom:
        - configMapRef:
            name: miniplayparty-api-config
        - secretRef:
            name: miniplayparty-api-secret
      containers:
      - name: miniplayparty-api
        image: ghcr.io/faisalhussain95/miniplayparty:main
        ports:
        - containerPort: 3336
        envFrom:
        - configMapRef:
            name: miniplayparty-api-config
        - secretRef:
            name: miniplayparty-api-secret
