apiVersion: v1
kind: Service
metadata:
  name: miniplayparty-api-service
spec:
  selector:
    app: miniplayparty-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3336
  type: LoadBalancer
