name: mini_play_party_server

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: miniplay
      POSTGRES_USER: miniplay
      POSTGRES_DB: miniplay
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
