name: mini_play_party_server

services:
  redis:
    image: redis
    environment:
      REDIS_ARGS: '--requirepass password'
    ports:
      - 6379:6379

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: miniplay
      POSTGRES_USER: miniplay
      POSTGRES_DB: miniplay
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 9000:8080
    environment:
      SWAGGER_JSON: /api/swagger.json
    volumes:
      - ./ressources/api_spec.yaml:/api/swagger.json
