apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "miniplay"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniplayparty-api-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          value: "miniplay"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        readinessProbe:
          exec:
            command: ["pg_isready", "-h", "localhost", "-U", "your-username"]
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
