apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: miniplayparty-api-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # Adjust the storage size as needed
